language: python
python:
    - 3.7
install: make setup
script:
    - make version
    - make test
branches:
    only:
        - master
notifications:
    email:
        on_success: never
        on_failure: change
